### ISSUE TITLE
Is there a way to dynamically build a list of articles or is that a WIP?

### ISSUE THREAD

**Issue by wolfejw86** [miayam/miayam#10]
Hey this is a cool template. I've read through the code for a while (I'm new to 11venty so forgive me if I've missed something) but I don't see anything currently present to dynamically render a series of blog articles. I see how the articles themselves get rendered but in terms of a page that basically does this:

![image](https://user-images.githubusercontent.com/22133869/108294186-64b1b180-7163-11eb-840b-d661d43577b8.png)

Am I missing something obvious or does this not exist yet in this template? If not no worries, just trying to sanity check myself here since I've been able to make sense about how the rest of this starter works.

Kudos on the design and really the system all together - I really like it!

**Comment by wolfejw86** [comment]
Okay - so adding to this, it seems there's a thing called collections and I can very easily iterate through all the articles with something like:
```
tags: ['articles']
```

which will then let me (pseudo code) {{ foreach article in collections.articles }} in the templates.
So this question could really be re-purposed to asking about what your plan is for the navigation component?

I started doing something like this -
![image](https://user-images.githubusercontent.com/22133869/108297798-cd9c2800-7169-11eb-8262-6613a562d30a.png)
But figured I was probably missing something from how navigation is supposed to work in atomic / brutalist design (both also very new comments to me).

Anyways, this starter you made is really cool and I'm mostly asking these questions just to try and learn new things.  Any guidance you can offer is much appreciated.

Cheers!

**Comment by miayam** [comment]
Thanks for the compliment. In my recent commit, I have written a config to iterate through the articles, build pagination and group them by tags. Here is the code to categorize the articles written on `.eleventy.js`:

```js
    config.addCollection('categories', (collection) => {
        // Get unique list of tags
        let tagSet = new Set();
        collection.getAllSorted().map(item => {
            if ("tags" in item.data) {
                const tags = item.data.tags;
                // Optionally filter things out before you iterate over.
                for (let tag of tags) {
                    tagSet.add(tag);
                }
            }
        });

        const paginationSize = 5;
        const tagMap = [];
        const tagArray = [...tagSet];

        for (let tagName of tagArray) {
            const tagItems = collection.getFilteredByTag(tagName);
            const pagedItems = chunk(tagItems, paginationSize);
            pagedItems.forEach((pagedItem, index) => {
                tagMap.push({
                    tagName,
                    pageNumber: index,
                    pageData: pagedItem
                });
            });
       }

       return tagMap;
    });
 ```
 
 Create a templete in folder `src/statics` and use `collections.categories`. This is how I build API using `Nunjucks` syntax:
 
 ```
---
pagination:
  data: collections.categories
  size: 1
  alias: tag
permalink: /tags/{{ tag.tagName }}/{% if tag.pageNumber %}{{ tag.pageNumber + 1 }}/{% endif %}index.json
---
{
    "posts": [
        {% for item in tag.pageData %}
            {
                "url": "{{ item.url }}",
                "content": "{{ item.templateContent | safe | stripHtml }}"
            }{% if not loop.last %},{% endif %}
        {% endfor %}
    ]
}
 ```
 
 And for navigation, I just use `permalink`, you can read it on [documentation]( https://www.11ty.dev/docs/permalinks/)
